config/routes.rb
Chefans::Application.routes.draw do

  get "sessions/new"

  resources :topics, only: [:index, :show, :create]
  resources :nodes, only: [:show]
  resources :users, only: [:show, :create]

  match "sign_up", to: "users#new"
  match "sign_in", to: "sessions#new"
  match "new_topic", to: "topics#new"
  root :to => 'topics#index'

  resources :sessions, only: [:create]

end

app/models/node.rb
class Node < ActiveRecord::Base
  attr_accessible :description, :name

  validates :name, :description, presence: true

  has_many :topics
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :content, :title, :node_id

  validates :title, :content, presence: true

  belongs_to :node
  belongs_to :author, class_name: "User", foreign_key: "user_id"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :username

  has_many :topics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    @current_user ||= User.find_by_username(session[:username]) if session[:username]
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  def show
    @node = Node.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    session[:username] = params[:username]
    redirect_to root_path
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    Topic.create(params[:topic])
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    User.create(params[:user])
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Chef Fans</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="banner">
    <%= image_tag("logo.png", size: "50x50") %>
    <%= link_to "Chef Fans", topics_path %>
    <%= link_to "Question", topics_path %>
    <%= link_to "Share", topics_path %>
  </div>

  <div id="columns">
    <div id="question">
      <h2>Question</h2>
      <p>ask a question<p>
      <%= yield %>
    </div>

  </div>
</body>
</html>

app/views/nodes/show.html.erb
<h2><%= @node.name %></h2>
<span><%= "there is #{@node.topics.count} topics" %></span>
<p><%= @node.description %></p>
<%= render 'topics/topic_list', topics: @node.topics %>

app/views/topics/_topic_list.html.erb
<% topics.each do |topic| %>
  <h2><%= link_to_unless_current topic.title, topic %></h2>
  <p><%= link_to topic.node.name, topic.node %>
  <p><%= link_to topic.author.username, topic.author %>
  <p><%= "published #{time_ago_in_words(topic.created_at)} ago" %></p>
<% end %>

app/views/topics/index.html.erb
<%= render 'topic_list', topics: @topics %>

app/views/topics/new.html.erb
<%= form_for(@topic) do |f| %>

  <%= f.label :title %>
  <%= f.select :node_id, options_for_select(Node.all.map {|node| [node.name, node.id]}) %>
  <%= f.text_field :title %><br />

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit "Save" %>
<% end %>

app/views/topics/show.html.erb
<h2><%= @topic.title %></h2>
<%= simple_format @topic.content %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :username, "Username" %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :email, "E-mail:" %>
    <%= f.email_field :email, placeholder: "foo@bar.com" %>
  </div>

  <div class="action">
    <%= f.submit "Registry" %>
  </div>
<% end %>

app/views/users/show.html.erb
<tr>
  <td>Username: <%= @user.username %></td><br />
  <td>Created_at: <%= @user.created_at %></td>
</tr>
<br />

<% @user.topics.each do |topic| %>
  <%= link_to topic.node.name, topic.node %>
  <%= link_to topic.title, topic %>
  <%= "published #{time_ago_in_words(topic.created_at)} ago" %><br />
<% end %>